spring:
  application:
    name: eureka-cluster
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://10.0.1.10:8761/eureka/,http://10.0.1.11:8761/eureka/,http://10.0.1.12:8761/eureka/
  instance:
    prefer-ip-address: true

---

spring:
  config:
    activate:
      on-profile: peer1
eureka:
  instance:
    hostname: 10.0.1.10

---

spring:
  config:
    activate:
      on-profile: peer2
eureka:
  instance:
    hostname: 10.0.1.11

---

spring:
  config:
    activate:
      on-profile: peer3
eureka:
  instance:
    hostname: 10.0.1.12